[project]
name="src"
version='0.0.1'
description="Global House Price Prediction Project"
authors=[{name="SG",email="gousepakshaikh14112002@gmail.com"}]

[tool.setuptools]
packages={ find={}}

[tool.setuptools.dynamic]
dependencies={file="requirements.txt"}